### ISSUE TITLE
How can I help with the vapi's files ?

### ISSUE THREAD

**Issue by SkyzohKey** [cmotc/tox-vapi#1]
Hey ! I would live to help u to recreate the tox vapi's un order to be able to use Toxcore along with Vala (which is a lovely language). 

What I'm wanting to know is how can I help ? :)

**Comment by cmotc** [comment]
I'm doing this in part to learn how to create vapi's myself, because I agree Vala is a lovely language and the ones from Venom are too far out of date. Since I'm learning too, it's hard for me to reccomend exactly where you could help most. So far I've created bindings for the structures in toxcore. Right now I'm learning how to create bindings for the callbacks, and researching which callbacks I need to implement and which ones are unnecessary in a wrapper. There are some commented out sections of code that correspond to some of the callbacks in https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.h, which is what I was planning to do next. If you want to do that, that'd be fine, but I welcome anything you'd like to contribute.

**Comment by SkyzohKeyx** [comment]
Did you have some tutorials about writing vapi bindings ? The gnome wiki isn't very clear on this point. 😩

**Comment by cmotc** [comment]
No, unfortunately, once I've worked it all out myself I'll write out a tutorial but for right now, I'll just show you what I'm doing with it. Gnome wiki is especially unclear on how to do function pointers properly so I've been experimenting. Basically, I took the newest, most complete version of the .vapi that Venom used(There's a copy in my repo as tox-1.0.vapi) which worked back in October of last year, so I looked up libtoxcore's code from about that time. (https://github.com/irungentoo/toxcore/tree/54fdf3bdd653ebf6e55d2cb93fcae41e68436e11). Then, when I pick something I want to add to the wrapper, I find the current version of the function(The one I need to bind), and either the old version of the function or a function that works similarly in the old version of the library. Then I compare them and try to work out how the binding works by a combination of imitation and experimentation.

**Comment by SkyzohKeyx** [comment]
I forked your repo and seen that the toxcore.vapi was badly formated, so i rewrote it entirely. You can find a more or less clean version here: https://github.com/ValaTox/tox-vapi :)

**Comment by cmotc** [comment]
Thanks for your help. I haven't had any time to work on this for weeks.

**Comment by cmotc** [comment]
I went ahead and pulled your stuff into my repo @SkyzohKeyx, and I saw you created an organization https://github.com/valatox. Since this is now entirely made up of your work, I'll just submit anything I do to you or there, whichever you prefer.

**Comment by SkyzohKeyx** [comment]
Do whatever you want :p. Sure help on ValaTox would really be appreciated but i doesn't force you to close this repo or stop to work on. This is your decision :)
